name: Build and Publish

# variables are define here
env:
  DOCKER_REPOSITORY_NAME: ghcr.io/hasunohana/common-backend:latest

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
#          context: /usr/local/app/
          context: .
          # Note: tags has to be all lower-case
          tags: |
            $DOCKER_REPOSITORY_NAME
          # build on feature branches, push only on main branch
#           push: ${{ github.ref == 'refs/heads/main' }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
